# Python para Finanzas y Ciencia de Datos

## Clase 6: tarea

Corina Anania | cori.anania@gmail.com

_Jueves 15 de octubre de 2020_

### Consigna parte 1

In [28]:
cliente = {
    "nombre": "Corina",
    "apellido": "Anania",
    "dni": 39126766,
    "mail": "cori.anania@gmail.com",
}

print(cliente)

{'nombre': 'Corina', 'apellido': 'Anania', 'dni': 39126766, 'mail': 'cori.anania@gmail.com'}

In [25]:
premios = {
    1: "iPad",
    2: "2 noches de hotel",
    3: "vestido",
    4: "zapatos",
    5: "libro",
    6: "sesión de spa",
    7: "desayuno",
    8: "big box",
    9: "bicicleta",
    10: "nail beauty",
}

In [147]:
import random

numero_premio = random.randint (1,10)
print("Número de premio: ", numero_premio)

Número de premio:  10

In [148]:
for premio in premios :
    if premio == numero_premio :
        print ("Felicitaciones " + cliente.get("nombre"))
        print ("Te has ganado un/a " + premios.get(numero_premio))
        break

Felicitaciones Corina
Te has ganado un/a nail beauty

In [149]:
for premio in premios :
    if premio != numero_premio:
        pass
    else:
        print ("Felicitaciones " + cliente.get("nombre"))
        print ("Te has ganado un/a " + premios.get(numero_premio))

Felicitaciones Corina
Te has ganado un/a nail beauty

In [153]:
# Requisitos extra 

numero = False

while True:
    if  numero:
        print ("Usted no ha sido el ganador")
    else:
        print ("Felicitaciones " + cliente.get("nombre"))
        print ("Te has ganado un/a " + premios.get(numero_premio))
        break

Felicitaciones Corina
Te has ganado un/a nail beauty

### Consigna parte 2

In [41]:
import pandas as pd

In [82]:
# Punto 1
clientes_df = pd.DataFrame({
    "Nombre" : ["David", "Antonela", "Marisa", "Santiago", "Gisela", "Anabela", "Elizabeth", "Facundo", 
                "Pablo", "Sofia", "Manuel", "Andres", "Martina", "Javier", "Pedro"],
    "Apellido": ["Lastra", "Arce", "Vignolo", "Pineda", "Mainero", "Bustamante", "Fernandez", "Rodriguez", 
               "Perotti", "Tonetti", "Riberi", "Alberecht", "Cerutti", "Gorgerino", "Knubel"],
    "DNI": [39126766, 39126504, 39126789, 39126001, 39126126, 39126256, 39126360, 39126480, 
            39126599, 39126600, 39126714, 39126853, 36126992, 39126654, 39126332],
    "Sexo": ["M", "F", "F", "M", "F", "F", "F", "M", 
            "M", "F", "M", "M", "F", "M", "M"],
    "Mail": ["david.l@gmail.com", "antonela.a@gmail.com", "marisa.v@gmail.com", "santiago.p@gmail.com", "gisela.m@gmail.com",
            "anabela.b@gmail.com", "elizabeth.f@gmail.com", "facundo.r@gmail.com", "pablo.p@gmail.com", "sofia.t@gmail.com",
            "manuel.r@gmail.com", "andres.a@gmail.com", "martina.c@gmail.com", "javier.g@gmail.com", "pedro.k@gmail.com"],
    "Fecha de nacimiento": ["27/06/1996", "02/04/1996", "30/08/1960", "14/01/1996", "26/06/1996", "12/08/1995", "10/02/1996",
                        "28/05/1996", "21/01/1996", "28/06/1996", "13/12/1995", "31/12/1998", "25/09/2000", "13/02/1969", 
                         "23/10/1998"],
    "Color favorito": ["azul", "rojo", "fucsia", "amarillo", "verde", "amarillo", "celeste", "negro", "rojo", "naranja", "azul",
                      "amarillo", "blanco", "verde", "lila"],
    "Sucursal asignada": ["Santa Fe 1", "Santa Fe 2", "Santa Fe 3", "Cordoba 1", "Cordoba 2", "Cordoba 3", "San Luis 1", "San Luis 2",
               "San Luis 3", "Catamarca 1", "Catamarca 2", "Catamarca 3", "Chaco 1", "Chaco 2", "Chaco 3"],
    "Lugar de nacimiento": ["Santa Fe", "Santa Fe", "Rosario", "Cordoba", "Carlos Paz", "Morteros", "San Luis", "Mercedes",
                         "San Luis", "Catamarca", "Recreo", "Catamarca", "Corrientes", "Resistencia", "Posadas"],
    "Estado civil": ["soltero", "soltero", "viuda", "casado", "casado", "soltero", "casado", "soltero", "soltero", 
                     "soltero", "casado", "soltero", "casado", "soltero", "soltero"],
})

In [83]:
clientes_df

,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
0,David,Lastra,39126766,M,david.l@gmail.com,27/06/1996,azul,Santa Fe 1,Santa Fe,soltero
1,Antonela,Arce,39126504,F,antonela.a@gmail.com,02/04/1996,rojo,Santa Fe 2,Santa Fe,soltero
2,Marisa,Vignolo,39126789,F,marisa.v@gmail.com,30/08/1960,fucsia,Santa Fe 3,Rosario,viuda
3,Santiago,Pineda,39126001,M,santiago.p@gmail.com,14/01/1996,amarillo,Cordoba 1,Cordoba,casado
4,Gisela,Mainero,39126126,F,gisela.m@gmail.com,26/06/1996,verde,Cordoba 2,Carlos Paz,casado
5,Anabela,Bustamante,39126256,F,anabela.b@gmail.com,12/08/1995,amarillo,Cordoba 3,Morteros,soltero
6,Elizabeth,Fernandez,39126360,F,elizabeth.f@gmail.com,10/02/1996,celeste,San Luis 1,San Luis,casado
7,Facundo,Rodriguez,39126480,M,facundo.r@gmail.com,28/05/1996,negro,San Luis 2,Mercedes,soltero
8,Pablo,Perotti,39126599,M,pablo.p@gmail.com,21/01/1996,rojo,San Luis 3,San Luis,soltero
9,Sofia,Tonetti,39126600,F,sofia.t@gmail.com,28/06/1996,naranja,Catamarca 1,Catamarca,soltero
10,Manuel,Riberi,39126714,M,manuel.r@gmail.com,13/12/1995,azul,Catamarca 2,Recreo,casado
11,Andres,Alberecht,39126853,M,andres.a@gmail.com,31/12/1998,amarillo,Catamarca 3,Catamarca,soltero
12,Martina,Cerutti,36126992,F,martina.c@gmail.com,25/09/2000,blanco,Chaco 1,Corrientes,casado
13,Javier,Gorgerino,39126654,M,javier.g@gmail.com,13/02/1969,verde,Chaco 2,Resistencia,soltero
14,Pedro,Knubel,39126332,M,pedro.k@gmail.com,23/10/1998,lila,Chaco 3,Posadas,soltero

In [84]:
clientes_df.index = pd.RangeIndex(1,16)
clientes_df

,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
1,David,Lastra,39126766,M,david.l@gmail.com,27/06/1996,azul,Santa Fe 1,Santa Fe,soltero
2,Antonela,Arce,39126504,F,antonela.a@gmail.com,02/04/1996,rojo,Santa Fe 2,Santa Fe,soltero
3,Marisa,Vignolo,39126789,F,marisa.v@gmail.com,30/08/1960,fucsia,Santa Fe 3,Rosario,viuda
4,Santiago,Pineda,39126001,M,santiago.p@gmail.com,14/01/1996,amarillo,Cordoba 1,Cordoba,casado
5,Gisela,Mainero,39126126,F,gisela.m@gmail.com,26/06/1996,verde,Cordoba 2,Carlos Paz,casado
6,Anabela,Bustamante,39126256,F,anabela.b@gmail.com,12/08/1995,amarillo,Cordoba 3,Morteros,soltero
7,Elizabeth,Fernandez,39126360,F,elizabeth.f@gmail.com,10/02/1996,celeste,San Luis 1,San Luis,casado
8,Facundo,Rodriguez,39126480,M,facundo.r@gmail.com,28/05/1996,negro,San Luis 2,Mercedes,soltero
9,Pablo,Perotti,39126599,M,pablo.p@gmail.com,21/01/1996,rojo,San Luis 3,San Luis,soltero
10,Sofia,Tonetti,39126600,F,sofia.t@gmail.com,28/06/1996,naranja,Catamarca 1,Catamarca,soltero
11,Manuel,Riberi,39126714,M,manuel.r@gmail.com,13/12/1995,azul,Catamarca 2,Recreo,casado
12,Andres,Alberecht,39126853,M,andres.a@gmail.com,31/12/1998,amarillo,Catamarca 3,Catamarca,soltero
13,Martina,Cerutti,36126992,F,martina.c@gmail.com,25/09/2000,blanco,Chaco 1,Corrientes,casado
14,Javier,Gorgerino,39126654,M,javier.g@gmail.com,13/02/1969,verde,Chaco 2,Resistencia,soltero
15,Pedro,Knubel,39126332,M,pedro.k@gmail.com,23/10/1998,lila,Chaco 3,Posadas,soltero

In [85]:
# Punto 2
clientes_df.head(3)

,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
1,David,Lastra,39126766,M,david.l@gmail.com,27/06/1996,azul,Santa Fe 1,Santa Fe,soltero
2,Antonela,Arce,39126504,F,antonela.a@gmail.com,02/04/1996,rojo,Santa Fe 2,Santa Fe,soltero
3,Marisa,Vignolo,39126789,F,marisa.v@gmail.com,30/08/1960,fucsia,Santa Fe 3,Rosario,viuda

In [86]:
# Punto 3
clientes_df.tail(3)

,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
13,Martina,Cerutti,36126992,F,martina.c@gmail.com,25/09/2000,blanco,Chaco 1,Corrientes,casado
14,Javier,Gorgerino,39126654,M,javier.g@gmail.com,13/02/1969,verde,Chaco 2,Resistencia,soltero
15,Pedro,Knubel,39126332,M,pedro.k@gmail.com,23/10/1998,lila,Chaco 3,Posadas,soltero

In [87]:
# Punto 4
clientes_df.dtypes

Nombre                 object
Apellido               object
DNI                     int64
Sexo                   object
Mail                   object
Fecha de nacimiento    object
Color favorito         object
Sucursal asignada      object
Lugar de nacimiento    object
Estado civil           object
dtype: object

In [99]:
# Punto 5
clientes_df.to_excel('datos-clientes-raw.xlsx')

In [100]:
# Punto 6
clientes_sucursales_df = pd.read_excel('datos-clientes-raw.xlsx')

---

In [101]:
clientes_sucursales_df

,Unnamed: 0,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
0,1,David,Lastra,39126766,M,david.l@gmail.com,27/06/1996,azul,Santa Fe 1,Santa Fe,soltero
1,2,Antonela,Arce,39126504,F,antonela.a@gmail.com,02/04/1996,rojo,Santa Fe 2,Santa Fe,soltero
2,3,Marisa,Vignolo,39126789,F,marisa.v@gmail.com,30/08/1960,fucsia,Santa Fe 3,Rosario,viuda
3,4,Santiago,Pineda,39126001,M,santiago.p@gmail.com,14/01/1996,amarillo,Cordoba 1,Cordoba,casado
4,5,Gisela,Mainero,39126126,F,gisela.m@gmail.com,26/06/1996,verde,Cordoba 2,Carlos Paz,casado
5,6,Anabela,Bustamante,39126256,F,anabela.b@gmail.com,12/08/1995,amarillo,Cordoba 3,Morteros,soltero
6,7,Elizabeth,Fernandez,39126360,F,elizabeth.f@gmail.com,10/02/1996,celeste,San Luis 1,San Luis,casado
7,8,Facundo,Rodriguez,39126480,M,facundo.r@gmail.com,28/05/1996,negro,San Luis 2,Mercedes,soltero
8,9,Pablo,Perotti,39126599,M,pablo.p@gmail.com,21/01/1996,rojo,San Luis 3,San Luis,soltero
9,10,Sofia,Tonetti,39126600,F,sofia.t@gmail.com,28/06/1996,naranja,Catamarca 1,Catamarca,soltero
10,11,Manuel,Riberi,39126714,M,manuel.r@gmail.com,13/12/1995,azul,Catamarca 2,Recreo,casado
11,12,Andres,Alberecht,39126853,M,andres.a@gmail.com,31/12/1998,amarillo,Catamarca 3,Catamarca,soltero
12,13,Martina,Cerutti,36126992,F,martina.c@gmail.com,25/09/2000,blanco,Chaco 1,Corrientes,casado
13,14,Javier,Gorgerino,39126654,M,javier.g@gmail.com,13/02/1969,verde,Chaco 2,Resistencia,soltero
14,15,Pedro,Knubel,39126332,M,pedro.k@gmail.com,23/10/1998,lila,Chaco 3,Posadas,soltero

In [102]:
clientes_sucursales_df.index = pd.RangeIndex(1,16)
clientes_sucursales_df

,Unnamed: 0,Nombre,Apellido,DNI,Sexo,Mail,Fecha de nacimiento,Color favorito,Sucursal asignada,Lugar de nacimiento,Estado civil
1,1,David,Lastra,39126766,M,david.l@gmail.com,27/06/1996,azul,Santa Fe 1,Santa Fe,soltero
2,2,Antonela,Arce,39126504,F,antonela.a@gmail.com,02/04/1996,rojo,Santa Fe 2,Santa Fe,soltero
3,3,Marisa,Vignolo,39126789,F,marisa.v@gmail.com,30/08/1960,fucsia,Santa Fe 3,Rosario,viuda
4,4,Santiago,Pineda,39126001,M,santiago.p@gmail.com,14/01/1996,amarillo,Cordoba 1,Cordoba,casado
5,5,Gisela,Mainero,39126126,F,gisela.m@gmail.com,26/06/1996,verde,Cordoba 2,Carlos Paz,casado
6,6,Anabela,Bustamante,39126256,F,anabela.b@gmail.com,12/08/1995,amarillo,Cordoba 3,Morteros,soltero
7,7,Elizabeth,Fernandez,39126360,F,elizabeth.f@gmail.com,10/02/1996,celeste,San Luis 1,San Luis,casado
8,8,Facundo,Rodriguez,39126480,M,facundo.r@gmail.com,28/05/1996,negro,San Luis 2,Mercedes,soltero
9,9,Pablo,Perotti,39126599,M,pablo.p@gmail.com,21/01/1996,rojo,San Luis 3,San Luis,soltero
10,10,Sofia,Tonetti,39126600,F,sofia.t@gmail.com,28/06/1996,naranja,Catamarca 1,Catamarca,soltero
11,11,Manuel,Riberi,39126714,M,manuel.r@gmail.com,13/12/1995,azul,Catamarca 2,Recreo,casado
12,12,Andres,Alberecht,39126853,M,andres.a@gmail.com,31/12/1998,amarillo,Catamarca 3,Catamarca,soltero
13,13,Martina,Cerutti,36126992,F,martina.c@gmail.com,25/09/2000,blanco,Chaco 1,Corrientes,casado
14,14,Javier,Gorgerino,39126654,M,javier.g@gmail.com,13/02/1969,verde,Chaco 2,Resistencia,soltero
15,15,Pedro,Knubel,39126332,M,pedro.k@gmail.com,23/10/1998,lila,Chaco 3,Posadas,soltero

In [103]:
# Punto 7
clientes_sucursales_df.drop(["Unnamed: 0", "Sexo", "Fecha de nacimiento", "Color favorito","Lugar de nacimiento", "Estado civil"], inplace=True, axis=1)

In [104]:
# Punto 8
clientes_sucursales_df.rename(columns={
    "Nombre": "Name",
    "Apellido": "Surname",
    "DNI": "ID",
    "Sucursal asignada": "Agency"
}, inplace=True)

In [105]:
clientes_sucursales_df

         Name     Surname        ID                   Mail       Agency
1       David      Lastra  39126766      david.l@gmail.com   Santa Fe 1
2    Antonela        Arce  39126504   antonela.a@gmail.com   Santa Fe 2
3      Marisa     Vignolo  39126789     marisa.v@gmail.com   Santa Fe 3
4    Santiago      Pineda  39126001   santiago.p@gmail.com    Cordoba 1
5      Gisela     Mainero  39126126     gisela.m@gmail.com    Cordoba 2
6     Anabela  Bustamante  39126256    anabela.b@gmail.com    Cordoba 3
7   Elizabeth   Fernandez  39126360  elizabeth.f@gmail.com   San Luis 1
8     Facundo   Rodriguez  39126480    facundo.r@gmail.com   San Luis 2
9       Pablo     Perotti  39126599      pablo.p@gmail.com   San Luis 3
10      Sofia     Tonetti  39126600      sofia.t@gmail.com  Catamarca 1
11     Manuel      Riberi  39126714     manuel.r@gmail.com  Catamarca 2
12     Andres   Alberecht  39126853     andres.a@gmail.com  Catamarca 3
13    Martina     Cerutti  36126992    martina.c@gmail.com      Chaco 1
14     Javier   Gorgerino  39126654     javier.g@gmail.com      Chaco 2
15      Pedro      Knubel  39126332      pedro.k@gmail.com      Chaco 3

In [106]:
# Punto 9
clientes_sucursales_df["message"] = "Estimado/a " + clientes_sucursales_df["Name"] + ": Queremos informarle que la sucursal " + clientes_sucursales_df["Agency"] + ", está adecuando sus protocolos para satisfacer las disposiciones del COE Provincial."

In [107]:
clientes_sucursales_df

,Name,Surname,ID,Mail,Agency,message
1,David,Lastra,39126766,david.l@gmail.com,Santa Fe 1,Estimado/a David: Queremos informarle que la s...
2,Antonela,Arce,39126504,antonela.a@gmail.com,Santa Fe 2,Estimado/a Antonela: Queremos informarle que l...
3,Marisa,Vignolo,39126789,marisa.v@gmail.com,Santa Fe 3,Estimado/a Marisa: Queremos informarle que la ...
4,Santiago,Pineda,39126001,santiago.p@gmail.com,Cordoba 1,Estimado/a Santiago: Queremos informarle que l...
5,Gisela,Mainero,39126126,gisela.m@gmail.com,Cordoba 2,Estimado/a Gisela: Queremos informarle que la ...
6,Anabela,Bustamante,39126256,anabela.b@gmail.com,Cordoba 3,Estimado/a Anabela: Queremos informarle que la...
7,Elizabeth,Fernandez,39126360,elizabeth.f@gmail.com,San Luis 1,Estimado/a Elizabeth: Queremos informarle que ...
8,Facundo,Rodriguez,39126480,facundo.r@gmail.com,San Luis 2,Estimado/a Facundo: Queremos informarle que la...
9,Pablo,Perotti,39126599,pablo.p@gmail.com,San Luis 3,Estimado/a Pablo: Queremos informarle que la s...
10,Sofia,Tonetti,39126600,sofia.t@gmail.com,Catamarca 1,Estimado/a Sofia: Queremos informarle que la s...
11,Manuel,Riberi,39126714,manuel.r@gmail.com,Catamarca 2,Estimado/a Manuel: Queremos informarle que la ...
12,Andres,Alberecht,39126853,andres.a@gmail.com,Catamarca 3,Estimado/a Andres: Queremos informarle que la ...
13,Martina,Cerutti,36126992,martina.c@gmail.com,Chaco 1,Estimado/a Martina: Queremos informarle que la...
14,Javier,Gorgerino,39126654,javier.g@gmail.com,Chaco 2,Estimado/a Javier: Queremos informarle que la ...
15,Pedro,Knubel,39126332,pedro.k@gmail.com,Chaco 3,Estimado/a Pedro: Queremos informarle que la s...

In [108]:
# Punto 10
clientes_sucursales_df.to_excel("lista-mails-protocolo.xlsx")

---

In [154]:
# Punto 11
transacciones_df = pd.read_csv("transacciones.csv")

In [155]:
transacciones_df

#NO ME SALIÓ BIEN :(

   nroCuenta;nroOperacion;monto;estado;;;;;;;;
0              1622;100;12000;aprobada;;;;;;;;
1               1452;101;7000;aprobada;;;;;;;;
2              1362;102;7500;rechazada;;;;;;;;
3            5896;103;36000;en proceso;;;;;;;;
4               1200;104;3600;aprobada;;;;;;;;
5              2365;105;54220;aprobada;;;;;;;;
6                 23;106;1200;aprobada;;;;;;;;
7               563;107;25000;aprobada;;;;;;;;
8              1452;108;7200;rechazada;;;;;;;;
9               6985;109;7500;aprobada;;;;;;;;
10               366;110;3630;aprobada;;;;;;;;
11             2524;111;10000;aprobada;;;;;;;;
12            1256;112;15000;rechazada;;;;;;;;
13             1478;113;59000;aprobada;;;;;;;;
14              9874;114;4500;aprobada;;;;;;;;
15               5632;115;100;aprobada;;;;;;;;
16            2365;116;3200;en proceso;;;;;;;;
17            1433;117;3700;en proceso;;;;;;;;
18             1255;118;14000;aprobada;;;;;;;;
19             1633;119;14500;aprobada;;;;;;;;
20             2643;120;14600;aprobada;;;;;;;;
21               238;121;9000;aprobada;;;;;;;;
22             3632;122;7515;rechazada;;;;;;;;
23           6598;123;23000;en proceso;;;;;;;;
24             5463;124;200;en proceso;;;;;;;;
25               2356;125;121;aprobada;;;;;;;;
26             236;126;15000;rechazada;;;;;;;;
27            2455;127;16300;rechazada;;;;;;;;
28             2563;128;17000;aprobada;;;;;;;;
29              1023;129;4400;aprobada;;;;;;;;
30             2365;130;23200;aprobada;;;;;;;;
31             2365;131;19000;aprobada;;;;;;;;
32             3265;132;24000;aprobada;;;;;;;;
33             2351;133;23650;aprobada;;;;;;;;
34           4520;134;24021;en proceso;;;;;;;;

<img src="https://cdn.memegenerator.es/imagenes/memes/full/3/73/3735271.jpg"/>

In [114]:
# Punto 12
transacciones_df.sort_values(by='monto', ascending=True)

KeyError: 'monto'

In [ ]:
# Punto 13
transacciones_df['monto'].plot.hist()

In [ ]:
# Punto 14
transacciones_df[transacciones_df['estado'] == 'aprobada']